kind: pipeline
name: default

platform:
  os: linux
  arch: amd64
  
steps:
  - name: install
    image: node
    commands:
      - npm i
  - name: test
    image: node
    commands:
      - npm run test
  - name: build
    image: node
    commands:
      - npm run build